language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a376ca4981aeb2a81ca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
