language: ruby
rvm:
  - ruby-head
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a376ca4981aeb2a81ca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script: CODECLIMATE_REPO_TOKEN=d819a1100b1567adf763b9f6b0e1af83dcb59a4bf5c3534748ed32e3bb6818f4 bundle exec rake

addons:
  srcclr: true
